version: '2'

services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper-0
    hostname: zookeeper-0
    ports:
    - "2181:2181"
    user: "0:0"
    volumes:
    #- "/home/tester/zookeeper:/bitnami/zookeeper"
    - "zookeeper_data:/bitnami"
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
    - ZOO_PORT_NUMBER=2181
    - ZOO_SERVER_ID=0
    - ZOO_SERVERS=zookeeper-0:2888:3888

  # zookeeper:
  #   image: bitnami/zookeeper:3.9
  #   container_name: zookeeper-1
  #   hostname: zookeeper-1
  #   ports:
  #   - "2182:2182"
  #   user: "0:0"
  #   volumes:
  #   - "/home/tester/zookeeper:/bitnami/zookeeper"
  #   #- "zookeeper_data:/bitnami"
  #   environment:
  #   - ALLOW_ANONYMOUS_LOGIN=yes
  #   - ZOO_PORT_NUMBER=2181
  #   - ZOO_SERVER_ID=0
  #   - ZOO_SERVERS=zookeeper-0:2888:3888,zookeeper-1:2888:3888

  kafka-0:
    image: bitnami/kafka:3.0.2
    container_name: kafka-0
    hostname: kafka-0
    ports:
    - "9093:9093"
    user: "0:0"
    volumes:
    - "kafka_data_0:/bitnami"
    #- "/home/tester/kafka_0:/bitnami/kafka"
    #- "/home/tester/kafka_0/logs:/opt/bitnami/kafka/logs"
    environment:
    - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-0:2181

    - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9093
    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:9092,EXTERNAL://localhost:9093
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

    - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    #- KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
    #- KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2

    depends_on:
    - zookeeper

  kafka-1:
    image: bitnami/kafka:3.0.2
    container_name: kafka-1
    hostname: kafka-1
    ports:
    - "9094:9094"
    user: "0:0"
    volumes:
    - "kafka_data_1:/bitnami"
    #- "/home/tester/kafka_1:/bitnami/kafka"
    #- "/home/tester/kafka_1/logs:/opt/bitnami/kafka/logs"
    environment:
    - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-0:2181

    - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9094
    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092,EXTERNAL://localhost:9094
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT


    - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    #- KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
    #- KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2

    depends_on:
    - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data_0:
    driver: local
  kafka_data_1:
    driver: local