networks:
  kafka_network:

volumes:
  Kafka-0:
    driver: local
  # Kafka-1:
  #   driver: local
  # Kafka-2:
  #   driver: local
    
services:
##Kafka 00
  Kafka-0:
    image: bitnami/kafka:3.4
    container_name: Kafka-0
    restart: no
    ports:
      - '10000:9094'
    environment:     
      - KAFKA_CFG_BROKER_ID=0
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_KRAFT_CLUSTER_ID=HsDBs9l6UUmQq7Y5E6bNlw
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@Kafka-0:9093 #,1@Kafka-1:9093,2@Kafka-2:9093
      - ALLOW_PLAINTEXT_LISTENER=yes

      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://Kafka-0:9092,EXTERNAL://127.0.0.1:10000
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT

      # - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      # - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      # - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - kafka_network
    volumes:
      - "Kafka-0:/bitnami/kafka"

# ##Kafka 01
#   Kafka-1:
#     image: bitnami/kafka:3.4
#     restart: always
#     container_name: Kafka-1
#     ports:
#       - '10001:9094'
#     environment:
#       - KAFKA_CFG_BROKER_ID=1
#       - KAFKA_CFG_NODE_ID=1
#       - KAFKA_KRAFT_CLUSTER_ID=HsDBs9l6UUmQq7Y5E6bNlw
#       - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@Kafka-0:9093,1@Kafka-1:9093,2@Kafka-2:9093
#       - ALLOW_PLAINTEXT_LISTENER=yes
#       - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
#       - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
#       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://Kafka-1:9092,EXTERNAL://127.0.0.1:10001
#       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
#       - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
#       - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
#       - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
#       - KAFKA_CFG_PROCESS_ROLES=controller,broker
#       - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#     networks:
#       - kafka_network
#     volumes:
#       - "Kafka-1:/bitnami/kafka"
# ##Kafka 02
#   Kafka-2:
#     image: bitnami/kafka:3.4
#     restart: always
#     container_name: Kafka-2
#     ports:
#       - '10002:9094'
#     environment:
#       - KAFKA_CFG_BROKER_ID=2
#       - KAFKA_CFG_NODE_ID=2
#       - KAFKA_KRAFT_CLUSTER_ID=HsDBs9l6UUmQq7Y5E6bNlw
#       - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@Kafka-0:9093,1@Kafka-1:9093,2@Kafka-2:9093
#       - ALLOW_PLAINTEXT_LISTENER=yes
#       - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
#       - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
#       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://Kafka-2:9092,EXTERNAL://127.0.0.1:10002
#       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
#       - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
#       - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
#       - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
#       - KAFKA_CFG_PROCESS_ROLES=controller,broker
#       - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#     networks:
#       - kafka_network
#     volumes:
#       - "Kafka-2:/bitnami/kafka"
      
  KafkaWebUiService:
    image: provectuslabs/kafka-ui:latest
    container_name: KafkaWebUiContainer
    restart: no
    ports:
      - '8086:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=Local-Kraft-Cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=Kafka-0:9092,Kafka-1:9092,Kafka-2:9092
      - DYNAMIC_CONFIG_ENABLED=true
      - KAFKA_CLUSTERS_0_AUDIT_TOPICAUDITENABLED=true
      - KAFKA_CLUSTERS_0_AUDIT_CONSOLEAUDITENABLED=true
      #- KAFKA_CLUSTERS_0_METRICS_PORT=9999
    depends_on:
      - Kafka-0
      # - Kafka-1
      # - Kafka-2
    networks:
      - kafka_network