scrape_configs:
- job_name: "prometheus"
  static_configs:
  - targets: ["localhost:9090"]

- job_name: 'Member_Write'
  metrics_path: '/actuator/prometheus'
  scheme: 'http'
  scrape_interval: 15s
  static_configs:
  - targets: ["host.docker.internal:8081"]

- job_name: 'Member_Read'
  metrics_path: '/actuator/prometheus'
  scheme: 'http'
  scrape_interval: 15s
  static_configs:
  - targets: ["host.docker.internal:8082"]
