version: "2"

services:
  elasticsearch-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch-1
    environment:
      - node.name=elasticsearch-1 
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch-2
      - cluster.initial_master_nodes=elasticsearch-1

      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=false
      - xpack.security.authc.api_key.enabled=false

    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data_1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elasticsearch

  elasticsearch-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch-2
    environment:
      - node.name=elasticsearch-2
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch-1
      - cluster.initial_master_nodes=elasticsearch-1, elasticsearch-2

      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=false
      - xpack.security.authc.api_key.enabled=false

    ports:
      - 9201:9200
      - 9301:9300

    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data_2:/usr/share/elasticsearch/data
    networks:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    ports:
      - 5601:5601
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    networks:
      - elasticsearch
    depends_on:
      - elasticsearch-1
      - elasticsearch-2

volumes:
  elasticsearch_data_1:
    driver: local
  elasticsearch_data_2:
    driver: local


networks:
  elasticsearch:
    name: elasticsearch_Net