version: '2'

services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    ports:
      - "2181:2181"
    user: "0:0"
    volumes:
      #- "/home/tester/zookeeper:/bitnami/zookeeper"
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-0:
    image: bitnami/kafka:3.0.2
    container_name: kafka
    ports:
      - "9094:9094"
    user: "0:0"
    volumes:
      - "kafka_data:/bitnami"
      #- "/home/tester/kafka_0:/bitnami/kafka"
      #- "/home/tester/kafka_0/logs:/opt/bitnami/kafka/logs"
    environment:
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_BROKER_ID=0
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181

      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094      
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:9092,EXTERNAL://localhost:9094      
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER 
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      #- KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      #- KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2

    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local